parameters:
    files_base_dir: files
    access_need_router:
        - lv_fondation_ugc
        - lv_fondation_invitation      
        - lv_fondation_showinvitation
        - lv_fondation_userdream
        - lv_fondation_dream
        - lv_fondation_journey
        - lv_fondation_ibeacon_entrance
        - lv_fondation_wechat_entrance
    start_date: 2015-06-16 00:00:01
    end_date: 2015-07-28 18:30:23
    start_date_ibeacon: 2015-06-16 00:00:01
    end_date_ibeacon: 2015-06-20 23:59:59
    send_message_start_date1: 2015-06-25 17:00:00
    send_message_end_date1: 2015-06-25 21:00:00
    send_message_start_date2: 2015-06-26 18:00:00
    send_message_end_date2: 2015-06-26 21:00:00
    send_message_start_date3: 2015-07-03 17:50:00
    send_message_end_date3: 2015-07-03 21:00:00