parameters:
    files_base_dir: files
    access_need_router:
        - lv_fondation_ugc
        - lv_fondation_invitation      
        - lv_fondation_showinvitation
        - lv_fondation_userdream
        - lv_fondation_dream
        - lv_fondation_journey
        - lv_fondation_ibeacon_entrance
        - lv_fondation_wechat_entrance
        - lv_fondation_journeyuserdream
    start_date: 2015-06-16 00:00:01
    end_date: 2015-07-28 18:30:23
    start_date_ibeacon: 2015-06-16 00:00:01
    end_date_ibeacon: 2015-06-20 23:59:59
    send_message_date:
        - { start: 2015-07-10 18:00:00, end: 2015-07-10 22:00:00 }
        - { start: 2015-07-11 18:00:00, end: 2015-07-11 22:00:00 }
        - { start: 2015-07-15 18:00:00, end: 2015-07-15 19:30:00 }
        - { start: 2015-07-16 18:00:00, end: 2015-07-16 22:00:00 }
        - { start: 2015-07-17 18:00:00, end: 2015-07-17 22:00:00 }