lv_fondation_ugc:
    path:     /ugc
    defaults: { _controller: LVFondationBundle:Page:ugc }
# lv_fondation_userinfo:
#     path:     /create/userinfo
#     defaults: { _controller: LVFondationBundle:Page:createUserInfo }
# lv_fondation_testevent:
#     path:     /test/event
#     defaults: { _controller: LVFondationBundle:Page:testEvent }
api_fondation_jssdk:
    path:     /api/jssdk
    defaults: { _controller: LVFondationBundle:Api:jssdk }
    methods: [GET]

api_fondation_invite:
    path:     /api/invite
    defaults: { _controller: LVFondationBundle:Api:invite }
    methods: [POST]

api_fondation_userinfo:
    path:     /api/userinfo
    defaults: { _controller: LVFondationBundle:Api:userInfo }
    methods: [POST]

api_fondation_userdream:
    path:     /api/userdream
    defaults: { _controller: LVFondationBundle:Api:userDream }
    methods: [POST]

api_fondation_dreamlike:
    path:     /api/dreamlike
    defaults: { _controller: LVFondationBundle:Api:dreamLike }
    methods: [POST]

api_fondation_dreamupdate:
    path:     /api/dreamupdate
    defaults: { _controller: LVFondationBundle:Api:userDreamUpdate }
    methods: [POST]