lv_fondation_index:
    path:     /
    defaults: { _controller: LVFondationBundle:Page:index }

lv_fondation_ugc:
    path:     /ugc
    defaults: { _controller: LVFondationBundle:Page:ugc }

lv_fondation_journey:
    path:     /journey
    defaults: { _controller: LVFondationBundle:Page:journey }

lv_fondation_journeyuserdream:
    path:     /journey/dream/{id}
    defaults: { _controller: LVFondationBundle:Page:journeyUserDream }

lv_fondation_userdream:
    path:     /dream/{id}
    defaults: { _controller: LVFondationBundle:Page:userDream }

lv_fondation_chapter1:
    path:     /chapter1
    defaults: { _controller: LVFondationBundle:Page:chapterOne }

lv_fondation_chapter2:
    path:     /chapter2
    defaults: { _controller: LVFondationBundle:Page:chapterTwo }

lv_fondation_chapter3:
    path:     /chapter3
    defaults: { _controller: LVFondationBundle:Page:chapterThree }

lv_fondation_chapter4:
    path:     /chapter4
    defaults: { _controller: LVFondationBundle:Page:chapterFour }

lv_fondation_invitation:
    path:     /invitation
    defaults: { _controller: LVFondationBundle:Page:invitation }

lv_fondation_showinvitation:
    path:     /invitation/show/{id}
    defaults: { _controller: LVFondationBundle:Page:invitationShow }

api_fondation_jssdk:
    path:     /api/jssdk
    defaults: { _controller: LVFondationBundle:Api:jssdk }
    methods: [GET]

api_fondation_invite:
    path:     /api/invite
    defaults: { _controller: LVFondationBundle:Api:invite }
    methods: [POST]

api_fondation_userinfo:
    path:     /api/userinfo
    defaults: { _controller: LVFondationBundle:Api:userInfo }
    methods: [POST]

api_fondation_userdream:
    path:     /api/userdream
    defaults: { _controller: LVFondationBundle:Api:userDream }
    methods: [POST]

api_fondation_dreamlike:
    path:     /api/dreamlike
    defaults: { _controller: LVFondationBundle:Api:dreamLike }
    methods: [POST]

api_fondation_dreamupdate:
    path:     /api/dreamupdate
    defaults: { _controller: LVFondationBundle:Api:userDreamUpdate }
    methods: [POST]

lv_fondation_wechat_entrance:
    path:     /wechat/entrance
    defaults: { _controller: LVFondationBundle:Page:wechatEntrance }

lv_fondation_ibeacon_entrance:
    path:     /ibeacon/entrance
    defaults: { _controller: LVFondationBundle:Page:ibeaconEntrance }
