# services:
#    lv_fondation.example:
#        class: LV\Bundle\FondationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    lv.page.listener:
        class: LV\Bundle\FondationBundle\EventListener\LVPageRequestListener
        arguments: [@router, @service_container, @lv.user.service, @same.wechat, @lv.mobile.detect]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    lv.api.listener:
        class: LV\Bundle\FondationBundle\EventListener\LVApiRequestListener
        arguments: [@router, @service_container, @lv.user.service]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    lv.user.service:
        class: LV\Bundle\FondationBundle\Services\User\UserService
        arguments: [@doctrine.orm.entity_manager, @request_stack]

    lv.image.service:
        class: LV\Bundle\FondationBundle\Services\Image\ImageService
        arguments: [@service_container]

    lv.mobile.detect:
        class: LV\Bundle\FondationBundle\Lib\MobileDetect\MobileDetect

    session.memcached:
        class: Memcached
        arguments:
            persistent_id: %session_memcached_prefix%
        calls:
            - [ addServer, [ %session_memcached_host%, %session_memcached_port% ]]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [@session.memcached, { prefix: %session_memcached_prefix%, expiretime: %session_memcached_expire% }]