parameters:
    appid: wxeb57276615f0d9f1
    appsecret: 42ac444f36a854b3dc3c66bdc59c98cc
    oauthApiUrl: https://open.weixin.qq.com/connect/oauth2/authorize?
    tokenApiUrl: https://api.weixin.qq.com/cgi-bin/token?
    ticketApiUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?
    accessTokenApiUrl: https://api.weixin.qq.com/sns/oauth2/access_token?