parameters:
    oauthApiUrl: https://open.weixin.qq.com/connect/oauth2/authorize?
    tokenApiUrl: https://api.weixin.qq.com/cgi-bin/token?
    ticketApiUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?
    accessTokenApiUrl: https://api.weixin.qq.com/sns/oauth2/access_token?
    userInfoApiUrl: https://api.weixin.qq.com/cgi-bin/user/info?
    templateid: fP293jFFvUnZgXya_9cxhhN0I4GsLMRscKHVbtMIeiU
    templateurl: http://www.baidu.com
    templatecolor: #FF0000
    templatetitle: 大标题
    templatehead: 活动名
    templateclick: 点击文字
    curio_oauth_uri: http://oauth.curio.im/v1/wx/web/auth/000cd2b6-31bd-4fa6-81e5-6d596ff90fb2
    curio_info_uri: http://oauth.curio.im/v1/wx/web/auth/1a48df46-0c14-48a0-9970-194d34442995
    curio_access_token: 6b45274d-2030-4fda-94c3-e773f16592ad
