same_wechat_oauth:
    path:     /same/wechat/oauth/{type}
    defaults: { _controller: SameWechatBundle:Wechat:oauth }

same_wechat_homepage:
    path:     /same/wechat/index
    defaults: { _controller: SameWechatBundle:Wechat:index }

same_wechat_callback:
    path:     /same/wechat/callback_userinfo
    defaults: { _controller: SameWechatBundle:Wechat:callback}

same_wechat_islogin:
    path:     /same/wechat/islogin
    defaults: { _controller: SameWechatBundle:Wechat:islogin }

same_wechat_jssdk:
    path:     /same/wechat/jssdk
    defaults: { _controller: SameWechatBundle:Wechat:jssdk }