lv_seven_homepage:
    path:     /
    defaults: { _controller: LVSevenBundle:Default:index }

lv_seven_pro:
    path:     /pro/{type}/{id}
    defaults: { _controller: LVSevenBundle:Default:pro }

lv_seven_desktop:
    path:     /desktop
    defaults: { _controller: LVSevenBundle:Default:desktop }
