same_admin_index:
    path:     /same/admin/index
    defaults: { _controller: SameAdminBundle:Default:index }
same_admin_login:
    path:     /same/admin/login
    defaults: { _controller: SameAdminBundle:Default:login }
same_admin_file:
    path:     /same/admin/file
    defaults: { _controller: SameAdminBundle:Default:file }
same_admin_upload:
    path:     /same/admin/upload
    defaults: { _controller: SameAdminBundle:Default:upload }
