same_session:
    resource: "@SameSessionBundle/Resources/config/routing.yml"
    prefix:   /

same_wechat:
    resource: "@SameWechatBundle/Resources/config/routing.yml"
    prefix:   /

lv_fondation:
    resource: "@LVFondationBundle/Resources/config/routing.yml"
    prefix:   /fondation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
