parameters:
    cvd_access_need_router:
        - lv_cvd_index
        - lv_cvd_share
        - lv_cvd_product
        - lv_cvd_create
    cvd_access_error_router:
        - lv_cvd_create
        - lv_cvd_share