lv_cvd_index:
    path:     /
    defaults: { _controller: LVCvdBundle:Page:index }

lv_cvd_product:
    path:     /product/{gender}
    defaults: { _controller: LVCvdBundle:Page:product }
    requirements: 
      gender: male|female

lv_cvd_create:
    path:     /create
    defaults: { _controller: LVCvdBundle:Page:create }

lv_cvd_share:
    path:     /share/{id}
    defaults: { _controller: LVCvdBundle:Page:share }

lv_cvd_save:
    path:     /save
    defaults: { _controller: LVCvdBundle:Api:save }

lv_cvd_sharelog:
    path:     /sharelog
    defaults: { _controller: LVCvdBundle:Api:share }

lv_cvd_error:
    path:     /desktop
    defaults: { _controller: LVCvdBundle:Page:error }