<?php

namespace LV\Bundle\FondationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DreamLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreamLikeRepository extends EntityRepository
{
}
