<?php

namespace LV\Bundle\FondationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function saveUserInfoByUserId($id) 
	{

	    $user = $this->find(2);

	    $em = $this->getEntityManager();
    	$userinfo = $em->getRepository('LVFondationBundle:UserInfo');
    	var_dump(get_class_methods($userinfo));exit;
        //$userinfo = new UserInfo();
        $userinfo->setName('沈浩东2');
        $userinfo->setEmail('albertshen@126');
        $userinfo->setCellphone('13524703157');
        $userinfo->setAddress('上海市嘉定区宝安公路2888弄153号');
        $userinfo->setUser($user);

        $em = $this->getDoctrine()->getManager();
        $em->persist($userinfo);
        $em->flush();
	}
}
