<?php

namespace LV\Bundle\FondationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserDreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDreamRepository extends EntityRepository
{
	public function retrieveDreamCount() {
		$query = $this->getEntityManager()
            ->createQuery(
            	'SELECT COUNT(ud.id) FROM LVFondationBundle:UserDream ud'
            	);
        $result = $query->getSingleScalarResult();
        return $result;
	}

	public function retrieveDefaultDreams($user, $limit) {

		$em = $this->getEntityManager();

		$query = $em
            ->createQuery(
            	'SELECT ud FROM LVFondationBundle:UserDream ud
            	WHERE ud.status = :status 
            	ORDER BY ud.id DESC'
            	)
            ->setParameter(':status', 1)
            ->setMaxResults($limit);
        $results = $query->getResult();
        
        $data = array();
        $i = 0;
        foreach($results as $result) {
        	$dream_id = $result->getId();
        	$data[$i]['dream_num'] = $dream_id;
        	$data[$i]['dream_id'] = $dream_id;
        	$data[$i]['content'] = $result->getContent();
        	$data[$i]['nickname'] = $result->getNickname();
        	$like = $em->getRepository('LVFondationBundle:DreamLike')->findOneBy(array('user' => $user->getId(), 'userdream' => $dream_id));
        	$data[$i]['isliked'] = $like ? 1 : 0;
        	$i++;
        }
        return $data;
	}
}

