<?php

namespace LV\Bundle\FondationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserDreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDreamRepository extends EntityRepository
{
	public function retrieveDreamCount() {
		$query = $this->getEntityManager()
            ->createQuery(
            	'SELECT COUNT(ud.id) FROM LVFondationBundle:UserDream ud'
            	);
        $result = $query->getSingleScalarResult();
        return $result;
	}
}
